USE yugioh;

-- COMANDO DML - INSERT, UPDATE e DELETE
INSERT INTO elemento_nome(Nome) VALUES
('Aqua'),
('Demonio'),
('Dragão'),
('Besta'),
('Besta Alada'),
('Mago'),
('Besta Guerreira'),
('Zumbi'),
('Psiquico'),
('Inseto'),
('Reptil'),
('Serpente Marinha'),
('Ciberoso'),
('Trovão'),
('Dinossauro'),
('Guerreiro'),
('Maquina'),
('Piro');

INSERT INTO tipos_cartas(tipo_carta_nome, tipo_carta_cor) VALUES
('Monstro Normal(1ª Seleção)',('rgba 255,255,224')),
('Monstro Com Efeitos (2ª Seleção)',('rgba 255,165,0')),
('Fusão (3ª Seleção)',('rgba 160,32,240')),
('Pendullum (4ª Seleção)',('rgba 255,165,0')),
('XYZ (5ª Seleção))',('rgba 10,10,10')),
('Syncro (6ª Seleção)',('rgba white')),
('Link (6ª Seleção)',('rgba 35,35,142')),
('Armadilha (7ª Seleção)',('rgba 255,203,219')),
('Magia (8ª Seleção)',('rgba 144,238,144'));

INSERT INTO carta(carta_numero, carta_nome, carta_descricao, carta_imagem) VALUES
(1, 1, 3, 'Mago Negro', 'O mago mais poderoso em termos de ataque e defesa. Conhecido por sua habilidade em lançar feitiços devastadores.', '\\yugiohdex\\asset\\magoNegro.webp'),
(2, 1, 3, 'Pequena Maga Negra', 'A aprendiz do Mago Negro, ela possui habilidades mágicas impressionantes e é uma combatente ágil.', '\\yugiohdex\\asset\\magaNegra.jpg'),
(3, 1, 3, 'Dragão Negro Dos Olhos Vermelhos', 'Um dragão feroz com olhos vermelhos brilhantes. Sua força e poder são temidos por todos os duelistas.', '\\yugiohdex\\asset\\dragaoNegro.webp'),
(4, 1, 3, 'Dragão Branco Dos Olhos Azuis', 'Um dragão lendário conhecido por sua força devastadora e ataques poderosos. Seus olhos azuis brilham com intensidade, intimidador para os adversários.', '\\yugiohdex\\asset\\dragaobranco.webp'),
(5, 1, 3, 'Dragão Definitivo De Olhos Azuis', 'A fusão de três Dragões Brancos de Olhos Azuis, este dragão possui um poder devastador e é praticamente invencível em batalha.', '\\yugiohdex\\asset\\dragaoSupremo.webp'),
(6, 1, 3, 'Dragão De 5 Cabeças', 'Um dragão com cinco cabeças, cada uma com um poder devastador. Ele é temido em batalhas por sua invencibilidade.', '\\yugiohdex\\asset\\dragao5.webp'),
(7, 1, 3, 'Gaia, O Cavaleiro Impetuoso', 'Um guerreiro de terra que empunha a força da natureza, sempre pronto para lutar ao lado dos seus aliados.', '\\yugiohdex\\asset\\gaia.webp'),
(8, 1, 3, 'Guerreiro Da Espada De Chama Dourada', 'Um guerreiro feroz com a habilidade de controlar chamas, suas espadas são tão afiadas quanto suas habilidades em batalha.', '\\yugiohdex\\asset\\guerreiroChama.webp'),
(9, 1, 3, 'Exodia, O Proibido', 'Uma entidade lendária, composta por várias partes, que pode levar um duelista à vitória instantânea quando reunida.', '\\yugiohdex\\asset\\exodia.webp'),
(10, 1, 3, 'Braço Esquerdo de Exodia', 'Uma das partes de Exodia, conhecido por seu imenso poder em batalha.', '\\yugiohdex\\asset\\bracoEsquerdo.webp'),
(11, 1, 3, 'Braço Direito de Exodia', 'Outra parte de Exodia, vital para a invocação do grande monstro.', '\\yugiohdex\\asset\\bracoDireito.webp'),
(12, 1, 3, 'Perna Esquerda de Exodia', 'Parte essencial de Exodia, cuja presença em um duelo pode mudar o jogo.', '\\yugiohdex\\asset\\pernaEsquerda.webp'),
(13, 1, 3, 'Perna Direita de Exodia', 'Mais uma parte crucial de Exodia, conhecida por sua força formidável.', '\\yugiohdex\\asset\\pernaDireita.webp'),
(14, 1, 3, 'Kuriboh Alado', 'Uma pequena criatura que pode se transformar em um escudo contra ataques, frequentemente utilizada por duelistas astutos.', '\\yugiohdex\\asset\\kuriboh.webp'),
(15, 1, 3, 'Mudança De Opinião', 'Um monstro astuto que pode inverter as situações, mudando o rumo da batalha com suas táticas.', '\\yugiohdex\\asset\\mudancaOpinia.webp'),
(16, 1, 3, 'Reviver Monstro', 'Um feitiço poderoso que pode trazer um monstro de volta à vida, mudando o destino da partida.', '\\yugiohdex\\asset\\reviverMonstro.webp'),
(17, 1, 3, 'Polimelização', 'Uma mágica que permite a fusão de monstros, criando seres ainda mais poderosos para a batalha.', '\\yugiohdex\\asset\\polimelizacao.webp'),
(18, 1, 3, 'Pote Da Ganância', 'Um artefato mágico que concede ao duelista recursos adicionais, aumentando suas chances de vitória.', '\\yugiohdex\\asset\\poteGanancia.webp'),
(19, 1, 3, 'Força Espelho', 'Uma habilidade que reflete ataques inimigos de volta, surpreendendo adversários descuidados.', '\\yugiohdex\\asset\\forcaEspelho.webp'),
(20, 1, 3, 'Cilindros Mágicos', 'Um recurso mágico que pode ser utilizado para proteger ou fortalecer monstros durante a batalha.', '\\yugiohdex\\asset\\cilindrosMagicos.webp'),
(21, 1, 3, 'Herói Elemental Homem Alado', 'Um herói poderoso que voa acima do campo de batalha, sempre pronto para lutar contra as forças do mal.', '\\yugiohdex\\asset\\heroiAlado.webp'),
(22, 1, 3, 'Herói Elemental Neos', 'Um monstro lendário conhecido por sua imensa força e habilidades únicas, capaz de superar qualquer desafio.', '\\yugiohdex\\asset\\heroiNeos.webp'),
(23, 1, 3, 'Dragão Cibernético', 'Um dragão tecnológico que combina força bruta com habilidades avançadas, um verdadeiro pesadelo para os oponentes.', '\\yugiohdex\\asset\\dragaoCibernetico.webp'),
(24, 1, 3, 'Ciber Dragão Final', 'Uma máquina de batalha imbatível, que traz a destruição com suas impressionantes habilidades tecnológicas.', '\\yugiohdex\\asset\\ciberDragaoFinal.webp'),
(25, 1, 3, 'Yubel', 'Uma entidade misteriosa que possui poderes de manipulação e controle, conhecida por sua complexidade emocional.', '\\yugiohdex\\asset\\yubel.webp'),
(26, 1, 3, 'Dragão Das Rosas Negras', 'Um dragão místico que se alimenta da escuridão e das sombras, sempre pronto para atacar.', '\\yugiohdex\\asset\\dragaoRosasNegras.webp'),
(27, 1, 3, 'Dragão Arquidemonio Vermelho', 'Um dragão de poder absoluto, cujos ataques incendeiam tudo ao seu redor.', '\\yugiohdex\\asset\\dragaoArquidemonioVermelho.webp'),
(28, 1, 3, 'Dragão Poeira Estelar', 'Um dragão que brilha como as estrelas, trazendo beleza e destruição por onde passa.', '\\yugiohdex\\asset\\dragaoPoeiraEstelar.webp'),
(29, 1, 2, 'Dragão Metálico Flamejante De Olhos Vermelhos', 'Um dragão feroz com farpas metálicas, conhecido por seus ataques flamejantes.', '\\yugiohdex\\asset\\dragaoMetalico.webp'),
(30, 1, 2, 'Dragão XYZ Da Rebelião Negra', 'Um dragão com habilidades de fusão que pode mudar o curso da batalha instantaneamente.', '\\yugiohdex\\asset\\dragaoXYZ.webp'),
(31, 1, 2, 'Número 39: Utopia', 'Um monstro lendário que simboliza a proteção e a força, capaz de enfrentar qualquer inimigo.', '\\yugiohdex\\asset\\utopia.webp'),
(32, 1, 1, 'Performapal Mago Pendulum', 'Um artista mágico que utiliza a força do pêndulo para desferir ataques poderosos.', '\\yugiohdex\\asset\\magoPendulum.webp'),
(33, 1, 1, 'Dragão Pêndulo De Olhos Anômolos', 'Um dragão enigmático com poderes sobrenaturais, desafiando qualquer um que se atreva a enfrentá-lo.', '\\yugiohdex\\asset\\dragaoPendulo.webp'),
(34, 1, 1, 'Dragão De Olhos Anômolos', 'Um dragão poderoso que desencadeia a destruição com sua força imensurável.', '\\yugiohdex\\asset\\dragaoOlhosAnomolos.webp'),
(35, 1, 3, 'Dragão Firewall', 'Um dragão que protege os aliados, utilizando chamas ardentes para repelir inimigos.', '\\yugiohdex\\asset\\dragaoFirewall.webp'),
(36, 1, 3, 'Aranha Link', 'Uma criatura astuta que tece armadilhas com habilidades únicas, sempre pronta para surpreender os oponentes.', '\\yugiohdex\\asset\\aranhaLink.webp');

INSERT INTO   VALUES
(1, 10), (1, 25),
(2, 10), (2, 25),
(3, 7), (3, 25),
(4, 7), (4, 25),
(5, 7), (5, 25),
(6, 7), (6, 27),
(7, 7), (7, 27),
(8, 20), (8,25),
(9, 2), (9, 26),
(10, 10), (10, 25),
(11, 10), (11, 25),
(12, 10), (12, 25),
(13, 10), (13, 25),
(14, 10), (14, 26),
(15, 33), 
(16, 33),
(17, 33),
(18, 33), 
(19, 32),
(20, 32),
(21, 20), (21, 27),
(22, 20), (22, 25),
(23, 21), (23, 26),
(24, 21), (24, 27),
(25, 6), (25, 26),
(26, 7), (26, 30),
(27, 7), (27, 30),
(28, 7), (29, 30),
(29, 7), (29, 29),
(30, 7), (30, 29),
(31, 20), (31, 29),
(32, 10), (32, 28),
(33, 7), (33, 28),
(34, 7), (34, 26),
(35, 7), (35, 31),
(36, 17), (36, 31);
